"""ai goods receipt pipeline

Revision ID: 38c538e7a93e
Revises: 3cf4cab11af2
Create Date: 2026-07-25 16:07:02.117669
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '38c538e7a93e'
down_revision: Union[str, None] = '3cf4cab11af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('request_metadata', sa.JSON(), nullable=False),
    sa.Column('response_metadata', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['document_processing_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_request_org_status_created', 'ai_requests', ['organization_id', 'status', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_requests_document_id'), 'ai_requests', ['document_id'], unique=False)
    op.create_index(op.f('ix_ai_requests_job_id'), 'ai_requests', ['job_id'], unique=False)
    op.create_index(op.f('ix_ai_requests_organization_id'), 'ai_requests', ['organization_id'], unique=False)
    op.create_table('ai_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('request_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('normalized_output', sa.JSON(), nullable=False),
    sa.Column('overall_confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('response_hash', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['ai_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_results_document_id'), 'ai_results', ['document_id'], unique=False)
    op.create_index(op.f('ix_ai_results_organization_id'), 'ai_results', ['organization_id'], unique=False)
    op.create_index(op.f('ix_ai_results_request_id'), 'ai_results', ['request_id'], unique=True)
    op.create_table('ai_tool_calls',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('ai_result_id', sa.String(length=36), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('result_summary', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ai_result_id'], ['ai_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_tool_call_org_created', 'ai_tool_calls', ['organization_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_tool_calls_ai_result_id'), 'ai_tool_calls', ['ai_result_id'], unique=False)
    op.create_index(op.f('ix_ai_tool_calls_organization_id'), 'ai_tool_calls', ['organization_id'], unique=False)
    op.create_table('goods_receipt_drafts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('ai_result_id', sa.String(length=36), nullable=False),
    sa.Column('document_number', sa.String(length=120), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('validation_issues', sa.JSON(), nullable=False),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ai_result_id'], ['ai_results.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipt_drafts_ai_result_id'), 'goods_receipt_drafts', ['ai_result_id'], unique=True)
    op.create_index(op.f('ix_goods_receipt_drafts_document_id'), 'goods_receipt_drafts', ['document_id'], unique=True)
    op.create_index(op.f('ix_goods_receipt_drafts_organization_id'), 'goods_receipt_drafts', ['organization_id'], unique=False)
    op.create_index('ix_receipt_draft_org_status_created', 'goods_receipt_drafts', ['organization_id', 'status', 'created_at'], unique=False)
    op.create_table('goods_receipt_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('draft_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('barcode', sa.String(length=128), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=80), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=False),
    sa.Column('matched_product_id', sa.String(length=36), nullable=True),
    sa.Column('packaging_unit_id', sa.String(length=36), nullable=True),
    sa.Column('conversion_factor', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('base_quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('match_method', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('validation_issues', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['goods_receipt_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['packaging_unit_id'], ['packaging_units.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'line_number', name='uq_receipt_item_line')
    )
    op.create_index(op.f('ix_goods_receipt_items_draft_id'), 'goods_receipt_items', ['draft_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_items_matched_product_id'), 'goods_receipt_items', ['matched_product_id'], unique=False)
    op.create_index(op.f('ix_goods_receipt_items_organization_id'), 'goods_receipt_items', ['organization_id'], unique=False)
    op.add_column('document_processing_jobs', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_processing_jobs', 'next_attempt_at')
    op.drop_index(op.f('ix_goods_receipt_items_organization_id'), table_name='goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipt_items_matched_product_id'), table_name='goods_receipt_items')
    op.drop_index(op.f('ix_goods_receipt_items_draft_id'), table_name='goods_receipt_items')
    op.drop_table('goods_receipt_items')
    op.drop_index('ix_receipt_draft_org_status_created', table_name='goods_receipt_drafts')
    op.drop_index(op.f('ix_goods_receipt_drafts_organization_id'), table_name='goods_receipt_drafts')
    op.drop_index(op.f('ix_goods_receipt_drafts_document_id'), table_name='goods_receipt_drafts')
    op.drop_index(op.f('ix_goods_receipt_drafts_ai_result_id'), table_name='goods_receipt_drafts')
    op.drop_table('goods_receipt_drafts')
    op.drop_index(op.f('ix_ai_tool_calls_organization_id'), table_name='ai_tool_calls')
    op.drop_index(op.f('ix_ai_tool_calls_ai_result_id'), table_name='ai_tool_calls')
    op.drop_index('ix_ai_tool_call_org_created', table_name='ai_tool_calls')
    op.drop_table('ai_tool_calls')
    op.drop_index(op.f('ix_ai_results_request_id'), table_name='ai_results')
    op.drop_index(op.f('ix_ai_results_organization_id'), table_name='ai_results')
    op.drop_index(op.f('ix_ai_results_document_id'), table_name='ai_results')
    op.drop_table('ai_results')
    op.drop_index(op.f('ix_ai_requests_organization_id'), table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_job_id'), table_name='ai_requests')
    op.drop_index(op.f('ix_ai_requests_document_id'), table_name='ai_requests')
    op.drop_index('ix_ai_request_org_status_created', table_name='ai_requests')
    op.drop_table('ai_requests')
    # ### end Alembic commands ###
