"""vrp import scheduling

Revision ID: d32d2adc9a69
Revises: 38c538e7a93e
Create Date: 2026-07-25 17:00:41.048828
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd32d2adc9a69'
down_revision: Union[str, None] = '38c538e7a93e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_product_mappings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('plugin_id', sa.String(length=80), nullable=False),
    sa.Column('external_key', sa.String(length=320), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('external_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_external_name', sa.String(length=255), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('conversion_factor', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('confirmed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'plugin_id', 'external_key', name='uq_external_mapping_org_plugin_key')
    )
    op.create_index(op.f('ix_external_product_mappings_normalized_external_name'), 'external_product_mappings', ['normalized_external_name'], unique=False)
    op.create_index(op.f('ix_external_product_mappings_organization_id'), 'external_product_mappings', ['organization_id'], unique=False)
    op.create_index(op.f('ix_external_product_mappings_product_id'), 'external_product_mappings', ['product_id'], unique=False)
    op.create_table('vrp_import_batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('canonical_items_hash', sa.String(length=64), nullable=False),
    sa.Column('parser_version', sa.String(length=40), nullable=False),
    sa.Column('external_report_id', sa.String(length=160), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.JSON(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=True),
    sa.Column('processed_by', sa.String(length=36), nullable=True),
    sa.Column('reversed_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reversed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reversed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'canonical_items_hash', name='uq_vrp_batch_org_canonical_hash'),
    sa.UniqueConstraint('organization_id', 'external_report_id', name='uq_vrp_batch_org_external_report'),
    sa.UniqueConstraint('organization_id', 'file_hash', name='uq_vrp_batch_org_file_hash')
    )
    op.create_index('ix_vrp_batch_org_period', 'vrp_import_batches', ['organization_id', 'period_start', 'period_end'], unique=False)
    op.create_index('ix_vrp_batch_org_status_scheduled', 'vrp_import_batches', ['organization_id', 'status', 'scheduled_for'], unique=False)
    op.create_index(op.f('ix_vrp_import_batches_canonical_items_hash'), 'vrp_import_batches', ['canonical_items_hash'], unique=False)
    op.create_index(op.f('ix_vrp_import_batches_file_hash'), 'vrp_import_batches', ['file_hash'], unique=False)
    op.create_index(op.f('ix_vrp_import_batches_organization_id'), 'vrp_import_batches', ['organization_id'], unique=False)
    op.create_table('vrp_import_schedules',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('processing_time', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('weekly_day', sa.String(length=16), nullable=False),
    sa.Column('monthly_rule', sa.String(length=16), nullable=False),
    sa.Column('auto_process', sa.Boolean(), nullable=False),
    sa.Column('unknown_product_policy', sa.String(length=32), nullable=False),
    sa.Column('negative_stock_policy', sa.String(length=32), nullable=False),
    sa.Column('overlap_policy', sa.String(length=20), nullable=False),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('organization_id')
    )
    op.create_table('vrp_import_errors',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('raw_row', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['vrp_import_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vrp_import_errors_batch_id'), 'vrp_import_errors', ['batch_id'], unique=False)
    op.create_index(op.f('ix_vrp_import_errors_organization_id'), 'vrp_import_errors', ['organization_id'], unique=False)
    op.create_table('vrp_import_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('external_product_id', sa.String(length=160), nullable=True),
    sa.Column('external_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_external_name', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=18, scale=3), nullable=False),
    sa.Column('unit', sa.String(length=80), nullable=False),
    sa.Column('matched_product_id', sa.String(length=36), nullable=True),
    sa.Column('conversion_factor', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('base_quantity', sa.Numeric(precision=18, scale=3), nullable=True),
    sa.Column('match_method', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('validation_issues', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['vrp_import_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('batch_id', 'line_number', name='uq_vrp_item_batch_line')
    )
    op.create_index(op.f('ix_vrp_import_items_batch_id'), 'vrp_import_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_vrp_import_items_matched_product_id'), 'vrp_import_items', ['matched_product_id'], unique=False)
    op.create_index(op.f('ix_vrp_import_items_organization_id'), 'vrp_import_items', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vrp_import_items_organization_id'), table_name='vrp_import_items')
    op.drop_index(op.f('ix_vrp_import_items_matched_product_id'), table_name='vrp_import_items')
    op.drop_index(op.f('ix_vrp_import_items_batch_id'), table_name='vrp_import_items')
    op.drop_table('vrp_import_items')
    op.drop_index(op.f('ix_vrp_import_errors_organization_id'), table_name='vrp_import_errors')
    op.drop_index(op.f('ix_vrp_import_errors_batch_id'), table_name='vrp_import_errors')
    op.drop_table('vrp_import_errors')
    op.drop_table('vrp_import_schedules')
    op.drop_index(op.f('ix_vrp_import_batches_organization_id'), table_name='vrp_import_batches')
    op.drop_index(op.f('ix_vrp_import_batches_file_hash'), table_name='vrp_import_batches')
    op.drop_index(op.f('ix_vrp_import_batches_canonical_items_hash'), table_name='vrp_import_batches')
    op.drop_index('ix_vrp_batch_org_status_scheduled', table_name='vrp_import_batches')
    op.drop_index('ix_vrp_batch_org_period', table_name='vrp_import_batches')
    op.drop_table('vrp_import_batches')
    op.drop_index(op.f('ix_external_product_mappings_product_id'), table_name='external_product_mappings')
    op.drop_index(op.f('ix_external_product_mappings_organization_id'), table_name='external_product_mappings')
    op.drop_index(op.f('ix_external_product_mappings_normalized_external_name'), table_name='external_product_mappings')
    op.drop_table('external_product_mappings')
    # ### end Alembic commands ###
